### ISSUE TITLE
Develop branch

### ISSUE THREAD

**Issue by arnaud-m** [chocoteam/samples#2]
The develop branch is missing. 
The master branch does not compile using the develop branch of choco-solver.

**Comment by cprudhom** [comment]
Fix in last commit

**Comment by arnaud-m** [comment]
I should have tell you. I have forked the project. So, we have fixed it twice ;)

**Comment by arnaud-m** [comment]
If I am right, the current version on the choco develop branch is 4.0.0.b. 
Do you want us to work directly on the samples/master ? Or do you prefer to create a develop branch ?
